-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_training_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  time_of_day integer,
  day_of_week integer,
  weather_condition text,
  temperature numeric,
  humidity integer,
  days_since_last_walk integer,
  current_streak integer,
  average_mood_last_week numeric,
  sleep_quality_last_night integer,
  stress_level integer,
  walks_this_week integer,
  walks_same_time_last_week integer,
  success_rate_last_month numeric,
  actually_walked boolean NOT NULL,
  session_id uuid,
  predicted_motivation numeric,
  model_version text,
  CONSTRAINT ai_training_data_pkey PRIMARY KEY (id),
  CONSTRAINT ai_training_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT ai_training_data_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.walking_sessions(id)
);
CREATE TABLE public.interventions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  type text NOT NULL CHECK (type = ANY (ARRAY['shorter_walk'::text, 'mindful_prompt'::text, 'progress_reminder'::text, 'weather_encouragement'::text, 'social_motivation'::text, 'reward_system'::text])),
  title text NOT NULL,
  message text NOT NULL,
  motivation_threshold numeric,
  time_of_day_start integer,
  time_of_day_end integer,
  weather_conditions ARRAY,
  times_shown integer DEFAULT 0,
  times_accepted integer DEFAULT 0,
  times_dismissed integer DEFAULT 0,
  effectiveness_score numeric DEFAULT 0,
  active boolean DEFAULT true,
  CONSTRAINT interventions_pkey PRIMARY KEY (id),
  CONSTRAINT interventions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.motivation_journal (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  date date NOT NULL,
  mood_rating integer CHECK (mood_rating >= 1 AND mood_rating <= 5),
  energy_level integer CHECK (energy_level >= 1 AND energy_level <= 5),
  motivation_level integer CHECK (motivation_level >= 1 AND motivation_level <= 5),
  weather_rating integer CHECK (weather_rating >= 1 AND weather_rating <= 5),
  sleep_quality integer CHECK (sleep_quality >= 1 AND sleep_quality <= 5),
  stress_level integer CHECK (stress_level >= 1 AND stress_level <= 5),
  notes text,
  goals_for_day text,
  walked_today boolean DEFAULT false,
  met_step_goal boolean DEFAULT false,
  CONSTRAINT motivation_journal_pkey PRIMARY KEY (id),
  CONSTRAINT motivation_journal_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  preferred_walk_duration integer DEFAULT 30,
  daily_step_goal integer DEFAULT 8000,
  notification_enabled boolean DEFAULT true,
  biometric_enabled boolean DEFAULT false,
  total_walks integer DEFAULT 0,
  total_distance numeric DEFAULT 0,
  total_steps integer DEFAULT 0,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  type text NOT NULL CHECK (type = ANY (ARRAY['daily_steps'::text, 'weekly_walks'::text, 'monthly_distance'::text, 'streak'::text, 'weight_loss'::text, 'custom'::text])),
  title text NOT NULL,
  description text,
  target_value numeric NOT NULL,
  current_value numeric DEFAULT 0,
  unit text,
  start_date date NOT NULL,
  target_date date NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'paused'::text, 'cancelled'::text])),
  completed_at timestamp with time zone,
  progress_percentage numeric DEFAULT 0,
  milestones jsonb,
  CONSTRAINT user_goals_pkey PRIMARY KEY (id),
  CONSTRAINT user_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.walking_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  duration integer,
  steps integer DEFAULT 0,
  distance numeric DEFAULT 0,
  average_pace numeric,
  calories_burned integer,
  route_coordinates jsonb,
  start_location jsonb,
  end_location jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'paused'::text, 'cancelled'::text])),
  weather_condition text,
  temperature numeric,
  humidity integer,
  pre_walk_mood integer CHECK (pre_walk_mood >= 1 AND pre_walk_mood <= 5),
  post_walk_mood integer CHECK (post_walk_mood >= 1 AND post_walk_mood <= 5),
  motivation_level integer CHECK (motivation_level >= 1 AND motivation_level <= 5),
  predicted_motivation numeric,
  intervention_applied text,
  intervention_effective boolean,
  CONSTRAINT walking_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT walking_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);